# Generated by Django 3.0 on 2019-12-11 19:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate_vs_base',
            field=models.DecimalField(decimal_places=9, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
